### ISSUE TITLE
Provide option to print upgradable packages as a simple list separated by spaces

### ISSUE THREAD

**Issue by superclarkk** [tjunnone/npm-check-updates#217]
Especially for use with the global (`-g`) option, it would be useful if `ncu` was able to print the upgradable packages as a simple list of package names, separated by spaces, (eg. `babel-eslint eslint grunt-cli jshint jslint`) so that it could be copied and pasted (and manually edited) to be used in an `npm install -g babel-eslint grunt-cli jshint jslint` command (note that `eslint` was removed, as it must not be upgraded).

**Comment by superclarkk** [comment]
btw, currently, I'm using the following, but it's a bit messy.
`ncu -g | cut -d' ' -f2 | tr '\n' ' '`

**Comment by metaraine** [comment]
The suggested solution is to use the --jsonUpgraded or --jsonAll flags to output JSON and then use a command line JSON parser combined with built-in command line tools to get the desired format. The JSON output is stable and building formatting conversions into ncu does not make sense when it can be accomplished with tools that are available within the *nix ecosystem.

**Comment by superclarkk** [comment]
I just tried that, but the command `ncu -g --jsonAll` doesn't output anything.

**Comment by metaraine** [comment]
Yeah, we should fix that.

**Comment by superclarkk** [comment]
"building formatting conversions into ncu does not make sense when it can be accomplished with tools that are available within the *nix ecosystem"

While I appreciate your point, it should be considered how ncu is actually used. It's fine if you want to upgrade all the packages that ncu states are out of date (ie `npm update -g`). However, in its present form, how would you suggest easily upgrading a _subset_ of global packages?

This would be much easier with the enhancement I'm suggesting (especially when #216 is fixed), and wouldn't require all users to develop their own solutions.

**Comment by metaraine** [comment]
That would be a reasonable feature to add. It's a lower priority for me, but I would accept a pull request from anyone who wants to add an `--outputNames` option for that functionality.

#216 needs to be fixed regardless.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Comment by superclarkk** [comment]
I presumed from your comment above that you were going to fix jsonAll, but it still doesn't work and I can't see any issue for it

**Comment by raineorshine** [comment]
@superclarkk Thanks, you're right! Just added #241.

**Comment by superclarkk** [comment]
Thank you! :)
